[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="user" type="ru.atott.combiq.web.security.CombiqUser" --]
[#-- @ftlvariable name="question" type="ru.atott.combiq.service.bean.Question" --]
[#-- @ftlvariable name="urlResolver" type="ru.atott.combiq.web.utils.RequestUrlResolver" --]
[#-- @ftlvariable name="post" type="ru.atott.combiq.service.bean.Post" --]
[#-- @ftlvariable name="permissionHelper" type="ru.atott.combiq.web.security.PermissionHelper" --]
